2020-01-23 22:32:22,391 INFO: Microblog startup [in /home/natrix/PycharmProjects/proj/app/__init__.py:79]
2020-01-23 22:36:33,706 INFO: Microblog startup [in /home/natrix/PycharmProjects/proj/app/__init__.py:79]
2020-01-23 22:41:09,149 INFO: Microblog startup [in /home/natrix/PycharmProjects/proj/app/__init__.py:79]
2020-01-23 22:41:14,832 ERROR: Exception on /search [GET] [in /home/natrix/PycharmProjects/proj/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/natrix/PycharmProjects/proj/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/natrix/PycharmProjects/proj/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/natrix/PycharmProjects/proj/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/natrix/PycharmProjects/proj/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/natrix/PycharmProjects/proj/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/natrix/PycharmProjects/proj/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/natrix/PycharmProjects/proj/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/natrix/PycharmProjects/proj/app/main/routes.py", line 155, in search
    current_app.config['POSTS_PER_PAGE'])
  File "/home/natrix/PycharmProjects/proj/app/models.py", line 92, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
  File "/home/natrix/PycharmProjects/proj/app/search.py", line 22, in query_index
    'from': (page - 1) * per_page, 'size': per_page})
  File "/home/natrix/PycharmProjects/proj/venv/lib/python3.7/site-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/natrix/PycharmProjects/proj/venv/lib/python3.7/site-packages/elasticsearch/client/__init__.py", line 1548, in search
    "GET", _make_path(index, doc_type, "_search"), params=params, body=body
  File "/home/natrix/PycharmProjects/proj/venv/lib/python3.7/site-packages/elasticsearch/transport.py", line 358, in perform_request
    timeout=timeout,
  File "/home/natrix/PycharmProjects/proj/venv/lib/python3.7/site-packages/elasticsearch/connection/http_urllib3.py", line 261, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/natrix/PycharmProjects/proj/venv/lib/python3.7/site-packages/elasticsearch/connection/base.py", line 182, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.NotFoundError: NotFoundError(404, 'index_not_found_exception', 'no such index [post]', post, index_or_alias)
2020-01-23 22:42:11,826 INFO: Microblog startup [in /home/natrix/PycharmProjects/proj/app/__init__.py:79]
2020-01-23 22:42:16,494 ERROR: Exception on /search [GET] [in /home/natrix/PycharmProjects/proj/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/natrix/PycharmProjects/proj/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/natrix/PycharmProjects/proj/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/natrix/PycharmProjects/proj/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/natrix/PycharmProjects/proj/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/natrix/PycharmProjects/proj/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/natrix/PycharmProjects/proj/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/natrix/PycharmProjects/proj/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/natrix/PycharmProjects/proj/app/main/routes.py", line 155, in search
    current_app.config['POSTS_PER_PAGE'])
  File "/home/natrix/PycharmProjects/proj/app/models.py", line 92, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
  File "/home/natrix/PycharmProjects/proj/app/search.py", line 22, in query_index
    'from': (page - 1) * per_page, 'size': per_page})
  File "/home/natrix/PycharmProjects/proj/venv/lib/python3.7/site-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/natrix/PycharmProjects/proj/venv/lib/python3.7/site-packages/elasticsearch/client/__init__.py", line 1548, in search
    "GET", _make_path(index, doc_type, "_search"), params=params, body=body
  File "/home/natrix/PycharmProjects/proj/venv/lib/python3.7/site-packages/elasticsearch/transport.py", line 358, in perform_request
    timeout=timeout,
  File "/home/natrix/PycharmProjects/proj/venv/lib/python3.7/site-packages/elasticsearch/connection/http_urllib3.py", line 261, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/natrix/PycharmProjects/proj/venv/lib/python3.7/site-packages/elasticsearch/connection/base.py", line 182, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.NotFoundError: NotFoundError(404, 'index_not_found_exception', 'no such index [post]', post, index_or_alias)
2020-01-23 22:51:05,008 ERROR: Exception on /search [GET] [in /home/natrix/PycharmProjects/proj/venv/lib/python3.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/natrix/PycharmProjects/proj/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/natrix/PycharmProjects/proj/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/natrix/PycharmProjects/proj/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/natrix/PycharmProjects/proj/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/natrix/PycharmProjects/proj/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/natrix/PycharmProjects/proj/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/natrix/PycharmProjects/proj/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/natrix/PycharmProjects/proj/app/main/routes.py", line 155, in search
    current_app.config['POSTS_PER_PAGE'])
  File "/home/natrix/PycharmProjects/proj/app/models.py", line 92, in search
    ids, total = query_index(cls.__tablename__, expression, page, per_page)
  File "/home/natrix/PycharmProjects/proj/app/search.py", line 22, in query_index
    'from': (page - 1) * per_page, 'size': per_page})
  File "/home/natrix/PycharmProjects/proj/venv/lib/python3.7/site-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/natrix/PycharmProjects/proj/venv/lib/python3.7/site-packages/elasticsearch/client/__init__.py", line 1548, in search
    "GET", _make_path(index, doc_type, "_search"), params=params, body=body
  File "/home/natrix/PycharmProjects/proj/venv/lib/python3.7/site-packages/elasticsearch/transport.py", line 358, in perform_request
    timeout=timeout,
  File "/home/natrix/PycharmProjects/proj/venv/lib/python3.7/site-packages/elasticsearch/connection/http_urllib3.py", line 261, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/natrix/PycharmProjects/proj/venv/lib/python3.7/site-packages/elasticsearch/connection/base.py", line 182, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.NotFoundError: NotFoundError(404, 'index_not_found_exception', 'no such index [post]', post, index_or_alias)
2020-01-23 22:52:19,161 INFO: Microblog startup [in /home/natrix/PycharmProjects/proj/app/__init__.py:77]
